"""
sql_agent/guardrails.py — Safety layer for all generated SQL.

Enforces:
  1. Regex blocklist: rejects any DDL or DML write operations
  2. Read-only SQLite connection (opened with ?mode=ro URI)
  3. Automatic LIMIT cap at settings.sql_max_rows
  4. Clear HTTP 400 error messages for blocked queries
"""
from __future__ import annotations

import re
import sqlite3
import logging

from fastapi import HTTPException

from config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()

# ─── Blocklist ────────────────────────────────────────────────────────────────
_WRITE_PATTERN = re.compile(
    r"\b(DROP|DELETE|UPDATE|INSERT|ALTER|TRUNCATE|CREATE|REPLACE|MERGE|ATTACH|DETACH|VACUUM|PRAGMA)\b",
    re.IGNORECASE,
)

# Comment stripping (avoid bypass via /* ... */ or -- comment tricks)
_COMMENT_PATTERN = re.compile(r"(--[^\n]*|/\*.*?\*/)", re.DOTALL)

_STACKED_QUERY_PATTERN = re.compile(r";.*\S", re.DOTALL)  # multiple statements


def validate_sql(sql: str) -> str:
    """
    Validate and sanitise SQL generated by the LLM.

    Args:
        sql: Raw SQL string from LLM.

    Returns:
        Sanitised SQL string (with LIMIT cap applied if missing).

    Raises:
        HTTPException(400): On any policy violation.
    """
    # Strip comments before checking
    clean_sql = _COMMENT_PATTERN.sub(" ", sql).strip()

    # Block stacked queries (multiple statements)
    if _STACKED_QUERY_PATTERN.search(clean_sql):
        logger.warning("BLOCKED: stacked query attempt: %s", clean_sql[:100])
        raise HTTPException(
            status_code=400,
            detail="SQL policy violation: multiple statements are not permitted.",
        )

    # Blocklist check
    match = _WRITE_PATTERN.search(clean_sql)
    if match:
        blocked_keyword = match.group(0).upper()
        logger.warning("BLOCKED: write operation '%s' in query: %s", blocked_keyword, clean_sql[:100])
        raise HTTPException(
            status_code=400,
            detail=f"SQL policy violation: '{blocked_keyword}' operations are not permitted. "
                   "Only SELECT queries are allowed.",
        )

    # Must start with SELECT (after stripping whitespace/comments)
    normalized = clean_sql.lstrip().upper()
    if not normalized.startswith("SELECT") and not normalized.startswith("WITH"):
        logger.warning("BLOCKED: non-SELECT query: %s", clean_sql[:100])
        raise HTTPException(
            status_code=400,
            detail="SQL policy violation: only SELECT (or WITH ... SELECT) queries are permitted.",
        )

    # Enforce row cap — append LIMIT if not already present
    safe_sql = _enforce_limit(clean_sql)
    return safe_sql


def _enforce_limit(sql: str) -> str:
    """Append LIMIT if not already present in the outermost query."""
    upper = sql.upper()
    if "LIMIT" not in upper:
        # Strip trailing semicolon before adding LIMIT
        sql = sql.rstrip().rstrip(";")
        sql = f"{sql}\nLIMIT {settings.sql_max_rows}"
        logger.debug("Auto-applied LIMIT %d to query", settings.sql_max_rows)
    return sql


def get_readonly_connection() -> sqlite3.Connection:
    """
    Open a read-only SQLite connection using the URI mode.
    This is enforced at the OS/SQLite driver level — writes are impossible.
    """
    uri = f"file:{settings.sqlite_db_path}?mode=ro"
    try:
        con = sqlite3.connect(uri, uri=True)
        con.row_factory = sqlite3.Row   # rows accessible by column name
        return con
    except sqlite3.OperationalError as e:
        logger.error("Cannot open read-only DB at %s: %s", settings.sqlite_db_path, e)
        raise HTTPException(
            status_code=503,
            detail=f"Database unavailable: {e}. Ensure the DB is seeded (run data/seed_db.py).",
        )


def execute_safe(sql: str) -> list[dict]:
    """
    Validate, then execute SQL on the read-only connection.

    Returns:
        List of row dicts, capped at sql_max_rows.
    """
    safe_sql = validate_sql(sql)
    con = get_readonly_connection()
    try:
        cur = con.execute(safe_sql)
        cols = [d[0] for d in cur.description] if cur.description else []
        rows = [dict(zip(cols, row)) for row in cur.fetchall()]
        return rows
    except sqlite3.Error as e:
        logger.error("SQL execution error: %s | Query: %s", e, safe_sql[:200])
        raise HTTPException(status_code=422, detail=f"SQL execution error: {e}")
    finally:
        con.close()
